apiVersion: k3d.io/v1alpha3
kind: Simple
name: go-cluster
servers: 1
agents: 2
kubeAPI: # same as `--api-port myhost.my.domain:6445` (where the name would resolve to 127.0.0.1)
  # host: "myhost.my.domain" # important for the `server` setting in the kubeconfig
  hostIP: "127.0.0.1"
  hostPort: "6445"
ports:
  - port: 8081:8080 # same as `--port '8081:80800@loadbalancer'`
    nodeFilters:
      - loadbalancer
